# Generated by Django 2.2.5 on 2019-09-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Login_status',
            field=models.BooleanField(default=False),
        ),
    ]
