# Generated by Django 2.2.5 on 2019-09-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='choice',
            order_with_respect_to='question',
        ),
    ]
